//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyFirstService")]
    public interface IMyFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        MyTestWcfServiceLibrary.CompositeType GetDataUsingDataContract(MyTestWcfServiceLibrary.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MyTestWcfServiceLibrary.CompositeType> GetDataUsingDataContractAsync(MyTestWcfServiceLibrary.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyFirstServiceChannel : GSP_SJ.ServiceReference1.IMyFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyFirstServiceClient : System.ServiceModel.ClientBase<GSP_SJ.ServiceReference1.IMyFirstService>, GSP_SJ.ServiceReference1.IMyFirstService {
        
        public MyFirstServiceClient() {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MyTestWcfServiceLibrary.CompositeType GetDataUsingDataContract(MyTestWcfServiceLibrary.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MyTestWcfServiceLibrary.CompositeType> GetDataUsingDataContractAsync(MyTestWcfServiceLibrary.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
