//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Replace
    {
        public int ID { get; set; }
        public Nullable<bool> RepEnable { get; set; }
        public string RepName { get; set; }
        public string RepSelect { get; set; }
        public string ReplaceTo { get; set; }
    }
}
