//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ProgramOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eng_ProgramOption()
        {
            this.Eng_ProgramOptionPicture = new HashSet<Eng_ProgramOptionPicture>();
        }
    
        public string ProductCode { get; set; }
        public string BoardSide { get; set; }
        public byte[] Picture { get; set; }
        public string PicturePath { get; set; }
        public string IsAdjusted { get; set; }
        public string P1 { get; set; }
        public Nullable<decimal> X1 { get; set; }
        public Nullable<decimal> Y1 { get; set; }
        public string P2 { get; set; }
        public Nullable<decimal> X2 { get; set; }
        public Nullable<decimal> Y2 { get; set; }
        public string P3 { get; set; }
        public Nullable<decimal> X3 { get; set; }
        public Nullable<decimal> Y3 { get; set; }
        public byte[] ANN { get; set; }
        public byte[] ReferencePicture { get; set; }
        public string ScanDPI { get; set; }
        public string P4 { get; set; }
        public Nullable<decimal> X4 { get; set; }
        public Nullable<decimal> Y4 { get; set; }
        public string P5 { get; set; }
        public Nullable<decimal> X5 { get; set; }
        public Nullable<decimal> Y5 { get; set; }
        public string P6 { get; set; }
        public Nullable<decimal> X6 { get; set; }
        public Nullable<decimal> Y6 { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<int> B1 { get; set; }
        public Nullable<int> B2 { get; set; }
        public Nullable<int> B3 { get; set; }
        public Nullable<int> B4 { get; set; }
        public Nullable<int> B5 { get; set; }
        public Nullable<int> B6 { get; set; }
        public Nullable<int> MarkType { get; set; }
        public Nullable<int> FixedPoint { get; set; }
        public Nullable<int> ScanStartX { get; set; }
        public Nullable<int> ScanStartY { get; set; }
        public string LP1 { get; set; }
        public Nullable<decimal> LX1 { get; set; }
        public Nullable<decimal> LY1 { get; set; }
        public string LP2 { get; set; }
        public Nullable<decimal> LX2 { get; set; }
        public Nullable<decimal> LY2 { get; set; }
        public string LP3 { get; set; }
        public Nullable<decimal> LX3 { get; set; }
        public Nullable<decimal> LY3 { get; set; }
        public string LP4 { get; set; }
        public Nullable<decimal> LX4 { get; set; }
        public Nullable<decimal> LY4 { get; set; }
        public string LP5 { get; set; }
        public Nullable<decimal> LX5 { get; set; }
        public Nullable<decimal> LY5 { get; set; }
        public string LP6 { get; set; }
        public Nullable<decimal> LX6 { get; set; }
        public Nullable<decimal> LY6 { get; set; }
        public Nullable<int> LB1 { get; set; }
        public Nullable<int> LB2 { get; set; }
        public Nullable<int> LB3 { get; set; }
        public Nullable<int> LB4 { get; set; }
        public Nullable<int> LB5 { get; set; }
        public Nullable<int> LB6 { get; set; }
        public Nullable<int> LFixedPoint { get; set; }
        public string LIsAdjusted { get; set; }
        public byte[] LPicture { get; set; }
        public Nullable<bool> ClockWise { get; set; }
        public Nullable<int> RGBR { get; set; }
        public Nullable<int> RGBG { get; set; }
        public Nullable<int> RGBB { get; set; }
        public decimal HeightCompensation { get; set; }
        public string LightSourceGroup { get; set; }
    
        public virtual Eng_Program Eng_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ProgramOptionPicture> Eng_ProgramOptionPicture { get; set; }
    }
}
