//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_StationTableItem
    {
        public string STCode { get; set; }
        public int Row { get; set; }
        public string DeviceNo { get; set; }
        public string StationCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Position { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Eng_StationTable Eng_StationTable { get; set; }
    }
}
