//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_XYData
    {
        public string ProductCode { get; set; }
        public string Position { get; set; }
        public int BoardId { get; set; }
        public string BoardSide { get; set; }
        public string IsSMD { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public Nullable<decimal> RX { get; set; }
        public Nullable<decimal> RY { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string StandardCode { get; set; }
        public Nullable<decimal> StandardRotation { get; set; }
        public string Size { get; set; }
        public string LcrType { get; set; }
        public string IsDefined { get; set; }
        public Nullable<decimal> OX { get; set; }
        public Nullable<decimal> OY { get; set; }
        public Nullable<decimal> OAngle { get; set; }
        public int Row { get; set; }
        public Nullable<decimal> LX { get; set; }
        public Nullable<decimal> LY { get; set; }
        public string IsMerge { get; set; }
        public byte[] StandardImage { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<decimal> FurnaceLcrStandardValue { get; set; }
        public string FurnaceLcrUnitCode { get; set; }
        public Nullable<decimal> FurnaceLcrMaxValue { get; set; }
        public Nullable<decimal> FurnaceLcrMinValue { get; set; }
        public Nullable<decimal> LXCompensation { get; set; }
        public Nullable<decimal> LYCompensation { get; set; }
        public string ComponentPackaging { get; set; }
        public Nullable<decimal> SX { get; set; }
        public Nullable<decimal> SY { get; set; }
        public Nullable<decimal> AdjustedAngle { get; set; }
        public int Groups { get; set; }
    
        public virtual Eng_Program Eng_Program { get; set; }
    }
}
