//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ParseRuleReplace
    {
        public string RuleCode { get; set; }
        public int Row { get; set; }
        public Nullable<int> PRI { get; set; }
        public string OldString { get; set; }
        public string NewString { get; set; }
        public string IsMatchULCase { get; set; }
        public string IsMatchSDCase { get; set; }
        public string IsEnabled { get; set; }
        public string Remarks { get; set; }
    
        public virtual Eng_ParseRule Eng_ParseRule { get; set; }
    }
}
