//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_BomSub
    {
        public string ProductCode { get; set; }
        public string MaterialCode { get; set; }
        public string SubMatCode { get; set; }
        public string SubMatName { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Status { get; set; }
    }
}
