//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_StationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eng_StationTable()
        {
            this.Eng_StationTableItem = new HashSet<Eng_StationTableItem>();
        }
    
        public string STCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string PLCode { get; set; }
        public string BoardSide { get; set; }
        public string PositionSeparator { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_StationTableItem> Eng_StationTableItem { get; set; }
    }
}
