//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FAI_NewEntities : DbContext
    {
        public FAI_NewEntities()
            : base("name=FAI_NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bas_CompensationValue> Bas_CompensationValue { get; set; }
        public virtual DbSet<Bas_Customer> Bas_Customer { get; set; }
        public virtual DbSet<Bas_DicIndex> Bas_DicIndex { get; set; }
        public virtual DbSet<Bas_DicItem> Bas_DicItem { get; set; }
        public virtual DbSet<Bas_DicRegister> Bas_DicRegister { get; set; }
        public virtual DbSet<Bas_Material> Bas_Material { get; set; }
        public virtual DbSet<Eng_Bom> Eng_Bom { get; set; }
        public virtual DbSet<Eng_BomECN> Eng_BomECN { get; set; }
        public virtual DbSet<Eng_BomReplace> Eng_BomReplace { get; set; }
        public virtual DbSet<Eng_BomSub> Eng_BomSub { get; set; }
        public virtual DbSet<Eng_Material> Eng_Material { get; set; }
        public virtual DbSet<Eng_Meter> Eng_Meter { get; set; }
        public virtual DbSet<Eng_MeterOption> Eng_MeterOption { get; set; }
        public virtual DbSet<Eng_MeterOptionItem> Eng_MeterOptionItem { get; set; }
        public virtual DbSet<Eng_Model> Eng_Model { get; set; }
        public virtual DbSet<Eng_ModelItem> Eng_ModelItem { get; set; }
        public virtual DbSet<Eng_ParseRule> Eng_ParseRule { get; set; }
        public virtual DbSet<Eng_ParseRuleExpression> Eng_ParseRuleExpression { get; set; }
        public virtual DbSet<Eng_ParseRuleReplace> Eng_ParseRuleReplace { get; set; }
        public virtual DbSet<Eng_ParseRuleSeparator> Eng_ParseRuleSeparator { get; set; }
        public virtual DbSet<Eng_ParseRuleToleranceC> Eng_ParseRuleToleranceC { get; set; }
        public virtual DbSet<Eng_ParseRuleToleranceL> Eng_ParseRuleToleranceL { get; set; }
        public virtual DbSet<Eng_ParseRuleToleranceR> Eng_ParseRuleToleranceR { get; set; }
        public virtual DbSet<Eng_PictureLibrary> Eng_PictureLibrary { get; set; }
        public virtual DbSet<Eng_Program> Eng_Program { get; set; }
        public virtual DbSet<Eng_ProgramLog> Eng_ProgramLog { get; set; }
        public virtual DbSet<Eng_ProgramOption> Eng_ProgramOption { get; set; }
        public virtual DbSet<Eng_ProgramOptionPicture> Eng_ProgramOptionPicture { get; set; }
        public virtual DbSet<Eng_PubModel> Eng_PubModel { get; set; }
        public virtual DbSet<Eng_PubModelItem> Eng_PubModelItem { get; set; }
        public virtual DbSet<Eng_Replace> Eng_Replace { get; set; }
        public virtual DbSet<Eng_StationTable> Eng_StationTable { get; set; }
        public virtual DbSet<Eng_StationTableItem> Eng_StationTableItem { get; set; }
        public virtual DbSet<Eng_XYData> Eng_XYData { get; set; }
        public virtual DbSet<Man_ComponentCheck> Man_ComponentCheck { get; set; }
        public virtual DbSet<Man_ComponentPackaging> Man_ComponentPackaging { get; set; }
        public virtual DbSet<Man_ComponentSize> Man_ComponentSize { get; set; }
        public virtual DbSet<Man_ComponentSizeItem> Man_ComponentSizeItem { get; set; }
        public virtual DbSet<Man_Report> Man_Report { get; set; }
        public virtual DbSet<Man_ReportInspectionItems> Man_ReportInspectionItems { get; set; }
        public virtual DbSet<Man_ReportItem> Man_ReportItem { get; set; }
        public virtual DbSet<Man_ReportLog> Man_ReportLog { get; set; }
        public virtual DbSet<Sys_Error> Sys_Error { get; set; }
        public virtual DbSet<Sys_Help> Sys_Help { get; set; }
        public virtual DbSet<Sys_Lang> Sys_Lang { get; set; }
        public virtual DbSet<Sys_Log> Sys_Log { get; set; }
        public virtual DbSet<Sys_Option> Sys_Option { get; set; }
        public virtual DbSet<Sys_OptionDDLB> Sys_OptionDDLB { get; set; }
        public virtual DbSet<Sys_Power> Sys_Power { get; set; }
        public virtual DbSet<Sys_Role> Sys_Role { get; set; }
        public virtual DbSet<Sys_RolePower> Sys_RolePower { get; set; }
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserLog> Sys_UserLog { get; set; }
        public virtual DbSet<View_Eng_Program> View_Eng_Program { get; set; }
    
        [DbFunction("FAI_NewEntities", "GetPoints")]
        public virtual IQueryable<GetPoints_Result> GetPoints(string bgId)
        {
            var bgIdParameter = bgId != null ?
                new ObjectParameter("BgId", bgId) :
                new ObjectParameter("BgId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPoints_Result>("[FAI_NewEntities].[GetPoints](@BgId)", bgIdParameter);
        }
    
        [DbFunction("FAI_NewEntities", "SplitStr")]
        public virtual IQueryable<SplitStr_Result> SplitStr(string sourceSql, string strSeprate)
        {
            var sourceSqlParameter = sourceSql != null ?
                new ObjectParameter("SourceSql", sourceSql) :
                new ObjectParameter("SourceSql", typeof(string));
    
            var strSeprateParameter = strSeprate != null ?
                new ObjectParameter("StrSeprate", strSeprate) :
                new ObjectParameter("StrSeprate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitStr_Result>("[FAI_NewEntities].[SplitStr](@SourceSql, @StrSeprate)", sourceSqlParameter, strSeprateParameter);
        }
    
        public virtual int P_Eng_BOMCheck(string productCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BOMCheck", productCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_BOMCompare(string productCode_Old, string productCode_New)
        {
            var productCode_OldParameter = productCode_Old != null ?
                new ObjectParameter("ProductCode_Old", productCode_Old) :
                new ObjectParameter("ProductCode_Old", typeof(string));
    
            var productCode_NewParameter = productCode_New != null ?
                new ObjectParameter("ProductCode_New", productCode_New) :
                new ObjectParameter("ProductCode_New", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BOMCompare", productCode_OldParameter, productCode_NewParameter);
        }
    
        public virtual int P_Eng_BomItemAdd(string productCode, string materialCode, string materialName, Nullable<int> quantity, string position, string remarks, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BomItemAdd", productCodeParameter, materialCodeParameter, materialNameParameter, quantityParameter, positionParameter, remarksParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_BomItemSubAdd(string productCode, string materialCode, string subMatCode, string subMatName, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var subMatCodeParameter = subMatCode != null ?
                new ObjectParameter("SubMatCode", subMatCode) :
                new ObjectParameter("SubMatCode", typeof(string));
    
            var subMatNameParameter = subMatName != null ?
                new ObjectParameter("SubMatName", subMatName) :
                new ObjectParameter("SubMatName", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BomItemSubAdd", productCodeParameter, materialCodeParameter, subMatCodeParameter, subMatNameParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_BomPositionRepeatCheck(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BomPositionRepeatCheck", productCodeParameter);
        }
    
        public virtual int P_Eng_BomQuantityCheck(string productCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_BomQuantityCheck", productCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_CheckBomMaterialAdd(string productCode, string materialCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_CheckBomMaterialAdd", productCodeParameter, materialCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_CheckBomMaterialExists(string productCode, string materialCode, string isIncludeSub, ObjectParameter isExists, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var isIncludeSubParameter = isIncludeSub != null ?
                new ObjectParameter("IsIncludeSub", isIncludeSub) :
                new ObjectParameter("IsIncludeSub", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_CheckBomMaterialExists", productCodeParameter, materialCodeParameter, isIncludeSubParameter, isExists, retVal, retMsg);
        }
    
        public virtual int P_Eng_GetPositionMaterial(string productCode, string position, ObjectParameter materialCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_GetPositionMaterial", productCodeParameter, positionParameter, materialCode, retVal, retMsg);
        }
    
        public virtual int P_Eng_GetPubModel(string xYCode, string bgID, string customerId)
        {
            var xYCodeParameter = xYCode != null ?
                new ObjectParameter("XYCode", xYCode) :
                new ObjectParameter("XYCode", typeof(string));
    
            var bgIDParameter = bgID != null ?
                new ObjectParameter("BgID", bgID) :
                new ObjectParameter("BgID", typeof(string));
    
            var customerIdParameter = customerId != null ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_GetPubModel", xYCodeParameter, bgIDParameter, customerIdParameter);
        }
    
        public virtual int P_Eng_GetXYCode(ObjectParameter xYCode)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_GetXYCode", xYCode);
        }
    
        public virtual int P_Eng_MatchMaterialCode(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_MatchMaterialCode", productCodeParameter);
        }
    
        public virtual int P_Eng_MeterOptionCopy(string newOptionName, string sourceOptionCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var newOptionNameParameter = newOptionName != null ?
                new ObjectParameter("NewOptionName", newOptionName) :
                new ObjectParameter("NewOptionName", typeof(string));
    
            var sourceOptionCodeParameter = sourceOptionCode != null ?
                new ObjectParameter("SourceOptionCode", sourceOptionCode) :
                new ObjectParameter("SourceOptionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_MeterOptionCopy", newOptionNameParameter, sourceOptionCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_MeterOptionDelete(string optionCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var optionCodeParameter = optionCode != null ?
                new ObjectParameter("OptionCode", optionCode) :
                new ObjectParameter("OptionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_MeterOptionDelete", optionCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_MeterOptionRename(string optionCode, string optionName, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var optionCodeParameter = optionCode != null ?
                new ObjectParameter("OptionCode", optionCode) :
                new ObjectParameter("OptionCode", typeof(string));
    
            var optionNameParameter = optionName != null ?
                new ObjectParameter("OptionName", optionName) :
                new ObjectParameter("OptionName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_MeterOptionRename", optionCodeParameter, optionNameParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_ParseRuleDelete(string ruleCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var ruleCodeParameter = ruleCode != null ?
                new ObjectParameter("RuleCode", ruleCode) :
                new ObjectParameter("RuleCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_ParseRuleDelete", ruleCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_ParseRuleRename(string ruleCode, string ruleName, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var ruleCodeParameter = ruleCode != null ?
                new ObjectParameter("RuleCode", ruleCode) :
                new ObjectParameter("RuleCode", typeof(string));
    
            var ruleNameParameter = ruleName != null ?
                new ObjectParameter("RuleName", ruleName) :
                new ObjectParameter("RuleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_ParseRuleRename", ruleCodeParameter, ruleNameParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_PictureLibraryCopy(string sourceXYCode, string targetXYCode, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var sourceXYCodeParameter = sourceXYCode != null ?
                new ObjectParameter("SourceXYCode", sourceXYCode) :
                new ObjectParameter("SourceXYCode", typeof(string));
    
            var targetXYCodeParameter = targetXYCode != null ?
                new ObjectParameter("TargetXYCode", targetXYCode) :
                new ObjectParameter("TargetXYCode", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_PictureLibraryCopy", sourceXYCodeParameter, targetXYCodeParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_QueryBomForward(string productCode, string expandSub)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var expandSubParameter = expandSub != null ?
                new ObjectParameter("ExpandSub", expandSub) :
                new ObjectParameter("ExpandSub", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_QueryBomForward", productCodeParameter, expandSubParameter);
        }
    
        public virtual int P_Eng_StandardCopy(string sourceXYCode, string targetXYCode, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var sourceXYCodeParameter = sourceXYCode != null ?
                new ObjectParameter("SourceXYCode", sourceXYCode) :
                new ObjectParameter("SourceXYCode", typeof(string));
    
            var targetXYCodeParameter = targetXYCode != null ?
                new ObjectParameter("TargetXYCode", targetXYCode) :
                new ObjectParameter("TargetXYCode", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_StandardCopy", sourceXYCodeParameter, targetXYCodeParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_StationTable_Add(string sTCode, string deviceNo, string stationCode, string materialCode, string materialName, Nullable<int> quantity, string position, string remarks, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var sTCodeParameter = sTCode != null ?
                new ObjectParameter("STCode", sTCode) :
                new ObjectParameter("STCode", typeof(string));
    
            var deviceNoParameter = deviceNo != null ?
                new ObjectParameter("DeviceNo", deviceNo) :
                new ObjectParameter("DeviceNo", typeof(string));
    
            var stationCodeParameter = stationCode != null ?
                new ObjectParameter("StationCode", stationCode) :
                new ObjectParameter("StationCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_StationTable_Add", sTCodeParameter, deviceNoParameter, stationCodeParameter, materialCodeParameter, materialNameParameter, quantityParameter, positionParameter, remarksParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_XYDataCompare(string xYCode)
        {
            var xYCodeParameter = xYCode != null ?
                new ObjectParameter("XYCode", xYCode) :
                new ObjectParameter("XYCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_XYDataCompare", xYCodeParameter);
        }
    
        public virtual int P_Eng_XYDataItemAdd(string xYCode, string position, string isSMD, Nullable<decimal> x, Nullable<decimal> y, Nullable<decimal> angle, string remarks, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var xYCodeParameter = xYCode != null ?
                new ObjectParameter("XYCode", xYCode) :
                new ObjectParameter("XYCode", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var isSMDParameter = isSMD != null ?
                new ObjectParameter("IsSMD", isSMD) :
                new ObjectParameter("IsSMD", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(decimal));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(decimal));
    
            var angleParameter = angle.HasValue ?
                new ObjectParameter("Angle", angle) :
                new ObjectParameter("Angle", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_XYDataItemAdd", xYCodeParameter, positionParameter, isSMDParameter, xParameter, yParameter, angleParameter, remarksParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_XYDataMaterialIdentify(string xYCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var xYCodeParameter = xYCode != null ?
                new ObjectParameter("XYCode", xYCode) :
                new ObjectParameter("XYCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_XYDataMaterialIdentify", xYCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Eng_XYDataQuantityCheck(string xYCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var xYCodeParameter = xYCode != null ?
                new ObjectParameter("XYCode", xYCode) :
                new ObjectParameter("XYCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Eng_XYDataQuantityCheck", xYCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_DeleteBoardMergeData(string productCode, string reportCode, string side, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var reportCodeParameter = reportCode != null ?
                new ObjectParameter("ReportCode", reportCode) :
                new ObjectParameter("ReportCode", typeof(string));
    
            var sideParameter = side != null ?
                new ObjectParameter("Side", side) :
                new ObjectParameter("Side", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_DeleteBoardMergeData", productCodeParameter, reportCodeParameter, sideParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_DoManualPassThisMaterials(string userName, string reportCode, string materialCode, string position, byte[] standardImage, byte[] currentImage, string productCode, string side, string isUpStandardImage, string isDefined, Nullable<int> boardId, string checkResult, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var reportCodeParameter = reportCode != null ?
                new ObjectParameter("ReportCode", reportCode) :
                new ObjectParameter("ReportCode", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var standardImageParameter = standardImage != null ?
                new ObjectParameter("StandardImage", standardImage) :
                new ObjectParameter("StandardImage", typeof(byte[]));
    
            var currentImageParameter = currentImage != null ?
                new ObjectParameter("CurrentImage", currentImage) :
                new ObjectParameter("CurrentImage", typeof(byte[]));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var sideParameter = side != null ?
                new ObjectParameter("Side", side) :
                new ObjectParameter("Side", typeof(string));
    
            var isUpStandardImageParameter = isUpStandardImage != null ?
                new ObjectParameter("IsUpStandardImage", isUpStandardImage) :
                new ObjectParameter("IsUpStandardImage", typeof(string));
    
            var isDefinedParameter = isDefined != null ?
                new ObjectParameter("IsDefined", isDefined) :
                new ObjectParameter("IsDefined", typeof(string));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var checkResultParameter = checkResult != null ?
                new ObjectParameter("CheckResult", checkResult) :
                new ObjectParameter("CheckResult", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_DoManualPassThisMaterials", userNameParameter, reportCodeParameter, materialCodeParameter, positionParameter, standardImageParameter, currentImageParameter, productCodeParameter, sideParameter, isUpStandardImageParameter, isDefinedParameter, boardIdParameter, checkResultParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_GetPositionList(string sTCode)
        {
            var sTCodeParameter = sTCode != null ?
                new ObjectParameter("STCode", sTCode) :
                new ObjectParameter("STCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_GetPositionList", sTCodeParameter);
        }
    
        public virtual int P_Man_GetReportCode(ObjectParameter reportCode)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_GetReportCode", reportCode);
        }
    
        public virtual int P_Man_GetSTCode(ObjectParameter sTCode)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_GetSTCode", sTCode);
        }
    
        public virtual int P_Man_ReportClose(string fBCCode, string isForce, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var fBCCodeParameter = fBCCode != null ?
                new ObjectParameter("FBCCode", fBCCode) :
                new ObjectParameter("FBCCode", typeof(string));
    
            var isForceParameter = isForce != null ?
                new ObjectParameter("IsForce", isForce) :
                new ObjectParameter("IsForce", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_ReportClose", fBCCodeParameter, isForceParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_ReportItemAdd(string fBCCode, string position, string materialCode, string materialName, Nullable<decimal> lcrStandardValue, string lcrUnitCode, Nullable<decimal> lcrMaxValue, Nullable<decimal> lcrMinValue, Nullable<decimal> lcrCheckValue, string resultType, string checkResult, string failCause, byte[] standardImage, byte[] currentImage, string remarks, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var fBCCodeParameter = fBCCode != null ?
                new ObjectParameter("FBCCode", fBCCode) :
                new ObjectParameter("FBCCode", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var lcrStandardValueParameter = lcrStandardValue.HasValue ?
                new ObjectParameter("LcrStandardValue", lcrStandardValue) :
                new ObjectParameter("LcrStandardValue", typeof(decimal));
    
            var lcrUnitCodeParameter = lcrUnitCode != null ?
                new ObjectParameter("LcrUnitCode", lcrUnitCode) :
                new ObjectParameter("LcrUnitCode", typeof(string));
    
            var lcrMaxValueParameter = lcrMaxValue.HasValue ?
                new ObjectParameter("LcrMaxValue", lcrMaxValue) :
                new ObjectParameter("LcrMaxValue", typeof(decimal));
    
            var lcrMinValueParameter = lcrMinValue.HasValue ?
                new ObjectParameter("LcrMinValue", lcrMinValue) :
                new ObjectParameter("LcrMinValue", typeof(decimal));
    
            var lcrCheckValueParameter = lcrCheckValue.HasValue ?
                new ObjectParameter("LcrCheckValue", lcrCheckValue) :
                new ObjectParameter("LcrCheckValue", typeof(decimal));
    
            var resultTypeParameter = resultType != null ?
                new ObjectParameter("ResultType", resultType) :
                new ObjectParameter("ResultType", typeof(string));
    
            var checkResultParameter = checkResult != null ?
                new ObjectParameter("CheckResult", checkResult) :
                new ObjectParameter("CheckResult", typeof(string));
    
            var failCauseParameter = failCause != null ?
                new ObjectParameter("FailCause", failCause) :
                new ObjectParameter("FailCause", typeof(string));
    
            var standardImageParameter = standardImage != null ?
                new ObjectParameter("StandardImage", standardImage) :
                new ObjectParameter("StandardImage", typeof(byte[]));
    
            var currentImageParameter = currentImage != null ?
                new ObjectParameter("CurrentImage", currentImage) :
                new ObjectParameter("CurrentImage", typeof(byte[]));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_ReportItemAdd", fBCCodeParameter, positionParameter, materialCodeParameter, materialNameParameter, lcrStandardValueParameter, lcrUnitCodeParameter, lcrMaxValueParameter, lcrMinValueParameter, lcrCheckValueParameter, resultTypeParameter, checkResultParameter, failCauseParameter, standardImageParameter, currentImageParameter, remarksParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_ReportSynBom(string reportCode, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var reportCodeParameter = reportCode != null ?
                new ObjectParameter("ReportCode", reportCode) :
                new ObjectParameter("ReportCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_ReportSynBom", reportCodeParameter, retVal, retMsg);
        }
    
        public virtual int P_Man_SynCoordinate(string sourceFBCCode, string targetFBCCode, string @operator, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var sourceFBCCodeParameter = sourceFBCCode != null ?
                new ObjectParameter("SourceFBCCode", sourceFBCCode) :
                new ObjectParameter("SourceFBCCode", typeof(string));
    
            var targetFBCCodeParameter = targetFBCCode != null ?
                new ObjectParameter("TargetFBCCode", targetFBCCode) :
                new ObjectParameter("TargetFBCCode", typeof(string));
    
            var operatorParameter = @operator != null ?
                new ObjectParameter("Operator", @operator) :
                new ObjectParameter("Operator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Man_SynCoordinate", sourceFBCCodeParameter, targetFBCCodeParameter, operatorParameter, retVal, retMsg);
        }
    
        public virtual int P_Sys_ChangePassword(string userCode, string passWord, string newPassWord, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var newPassWordParameter = newPassWord != null ?
                new ObjectParameter("NewPassWord", newPassWord) :
                new ObjectParameter("NewPassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_ChangePassword", userCodeParameter, passWordParameter, newPassWordParameter, retVal, retMsg);
        }
    
        public virtual int P_Sys_CheckPower(string userCode, string className, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var classNameParameter = className != null ?
                new ObjectParameter("ClassName", className) :
                new ObjectParameter("ClassName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_CheckPower", userCodeParameter, classNameParameter, retVal, retMsg);
        }
    
        public virtual int P_Sys_CheckUser(string userCode, string passWord, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_CheckUser", userCodeParameter, passWordParameter, retVal, retMsg);
        }
    
        public virtual int P_Sys_DataClear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DataClear");
        }
    
        public virtual int P_Sys_GetHelpCode(ObjectParameter helpCode)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_GetHelpCode", helpCode);
        }
    
        public virtual int P_Insert_Eng_Program(string productCode, string productName, string customerCode, string boardSide, string ruleCode, string status, string remarks, string creator, string modifier)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("CustomerCode", customerCode) :
                new ObjectParameter("CustomerCode", typeof(string));
    
            var boardSideParameter = boardSide != null ?
                new ObjectParameter("BoardSide", boardSide) :
                new ObjectParameter("BoardSide", typeof(string));
    
            var ruleCodeParameter = ruleCode != null ?
                new ObjectParameter("RuleCode", ruleCode) :
                new ObjectParameter("RuleCode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var creatorParameter = creator != null ?
                new ObjectParameter("Creator", creator) :
                new ObjectParameter("Creator", typeof(string));
    
            var modifierParameter = modifier != null ?
                new ObjectParameter("Modifier", modifier) :
                new ObjectParameter("Modifier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Insert_Eng_Program", productCodeParameter, productNameParameter, customerCodeParameter, boardSideParameter, ruleCodeParameter, statusParameter, remarksParameter, creatorParameter, modifierParameter);
        }
    
        public virtual ObjectResult<P_Search_Eng_Program_Result> P_Search_Eng_Program()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Search_Eng_Program_Result>("P_Search_Eng_Program");
        }
    
        public virtual int P_Insert_Eng_Bom(string productCode, Nullable<int> row, string materialCode, string materialName, Nullable<int> quantity, string position, string allowSubstitute, string lcrType, Nullable<decimal> lcrStandardValue, string lcrUnitCode, Nullable<decimal> lcrMaxValue, Nullable<decimal> lcrMinValue, string size, string remarks, string creator, string modifier, Nullable<decimal> maxTolerance, Nullable<decimal> minTolerance, string status, string screenPrinting, string toleranceType, string componentPackaging)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var rowParameter = row.HasValue ?
                new ObjectParameter("Row", row) :
                new ObjectParameter("Row", typeof(int));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var allowSubstituteParameter = allowSubstitute != null ?
                new ObjectParameter("AllowSubstitute", allowSubstitute) :
                new ObjectParameter("AllowSubstitute", typeof(string));
    
            var lcrTypeParameter = lcrType != null ?
                new ObjectParameter("LcrType", lcrType) :
                new ObjectParameter("LcrType", typeof(string));
    
            var lcrStandardValueParameter = lcrStandardValue.HasValue ?
                new ObjectParameter("LcrStandardValue", lcrStandardValue) :
                new ObjectParameter("LcrStandardValue", typeof(decimal));
    
            var lcrUnitCodeParameter = lcrUnitCode != null ?
                new ObjectParameter("LcrUnitCode", lcrUnitCode) :
                new ObjectParameter("LcrUnitCode", typeof(string));
    
            var lcrMaxValueParameter = lcrMaxValue.HasValue ?
                new ObjectParameter("LcrMaxValue", lcrMaxValue) :
                new ObjectParameter("LcrMaxValue", typeof(decimal));
    
            var lcrMinValueParameter = lcrMinValue.HasValue ?
                new ObjectParameter("LcrMinValue", lcrMinValue) :
                new ObjectParameter("LcrMinValue", typeof(decimal));
    
            var sizeParameter = size != null ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var creatorParameter = creator != null ?
                new ObjectParameter("Creator", creator) :
                new ObjectParameter("Creator", typeof(string));
    
            var modifierParameter = modifier != null ?
                new ObjectParameter("Modifier", modifier) :
                new ObjectParameter("Modifier", typeof(string));
    
            var maxToleranceParameter = maxTolerance.HasValue ?
                new ObjectParameter("MaxTolerance", maxTolerance) :
                new ObjectParameter("MaxTolerance", typeof(decimal));
    
            var minToleranceParameter = minTolerance.HasValue ?
                new ObjectParameter("MinTolerance", minTolerance) :
                new ObjectParameter("MinTolerance", typeof(decimal));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var screenPrintingParameter = screenPrinting != null ?
                new ObjectParameter("ScreenPrinting", screenPrinting) :
                new ObjectParameter("ScreenPrinting", typeof(string));
    
            var toleranceTypeParameter = toleranceType != null ?
                new ObjectParameter("ToleranceType", toleranceType) :
                new ObjectParameter("ToleranceType", typeof(string));
    
            var componentPackagingParameter = componentPackaging != null ?
                new ObjectParameter("ComponentPackaging", componentPackaging) :
                new ObjectParameter("ComponentPackaging", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Insert_Eng_Bom", productCodeParameter, rowParameter, materialCodeParameter, materialNameParameter, quantityParameter, positionParameter, allowSubstituteParameter, lcrTypeParameter, lcrStandardValueParameter, lcrUnitCodeParameter, lcrMaxValueParameter, lcrMinValueParameter, sizeParameter, remarksParameter, creatorParameter, modifierParameter, maxToleranceParameter, minToleranceParameter, statusParameter, screenPrintingParameter, toleranceTypeParameter, componentPackagingParameter);
        }
    
        public virtual int P_Insert_Eng_XYData(string productCode, string position, Nullable<int> boardId, string boardSide, string isSMD, string materialCode, string materialName, Nullable<decimal> x, Nullable<decimal> y, string unit, Nullable<decimal> angle, Nullable<decimal> rX, Nullable<decimal> rY, string remarks, string creator, string modifier, string standardCode, Nullable<decimal> standardRotation, string size, string lcrType, string isDefined, Nullable<decimal> oX, Nullable<decimal> oY, Nullable<decimal> oAngle, Nullable<int> row, Nullable<decimal> lX, Nullable<decimal> lY, string isMerge, byte[] standardImage, Nullable<int> sequence, Nullable<decimal> furnaceLcrStandardValue, string furnaceLcrUnitCode, Nullable<decimal> furnaceLcrMaxValue, Nullable<decimal> furnaceLcrMinValue, Nullable<decimal> lXCompensation, Nullable<decimal> lYCompensation, string componentPackaging, Nullable<decimal> sX, Nullable<decimal> sY, Nullable<decimal> adjustedAngle, Nullable<int> groups)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(string));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var boardSideParameter = boardSide != null ?
                new ObjectParameter("BoardSide", boardSide) :
                new ObjectParameter("BoardSide", typeof(string));
    
            var isSMDParameter = isSMD != null ?
                new ObjectParameter("IsSMD", isSMD) :
                new ObjectParameter("IsSMD", typeof(string));
    
            var materialCodeParameter = materialCode != null ?
                new ObjectParameter("MaterialCode", materialCode) :
                new ObjectParameter("MaterialCode", typeof(string));
    
            var materialNameParameter = materialName != null ?
                new ObjectParameter("MaterialName", materialName) :
                new ObjectParameter("MaterialName", typeof(string));
    
            var xParameter = x.HasValue ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(decimal));
    
            var yParameter = y.HasValue ?
                new ObjectParameter("Y", y) :
                new ObjectParameter("Y", typeof(decimal));
    
            var unitParameter = unit != null ?
                new ObjectParameter("Unit", unit) :
                new ObjectParameter("Unit", typeof(string));
    
            var angleParameter = angle.HasValue ?
                new ObjectParameter("Angle", angle) :
                new ObjectParameter("Angle", typeof(decimal));
    
            var rXParameter = rX.HasValue ?
                new ObjectParameter("RX", rX) :
                new ObjectParameter("RX", typeof(decimal));
    
            var rYParameter = rY.HasValue ?
                new ObjectParameter("RY", rY) :
                new ObjectParameter("RY", typeof(decimal));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var creatorParameter = creator != null ?
                new ObjectParameter("Creator", creator) :
                new ObjectParameter("Creator", typeof(string));
    
            var modifierParameter = modifier != null ?
                new ObjectParameter("Modifier", modifier) :
                new ObjectParameter("Modifier", typeof(string));
    
            var standardCodeParameter = standardCode != null ?
                new ObjectParameter("StandardCode", standardCode) :
                new ObjectParameter("StandardCode", typeof(string));
    
            var standardRotationParameter = standardRotation.HasValue ?
                new ObjectParameter("StandardRotation", standardRotation) :
                new ObjectParameter("StandardRotation", typeof(decimal));
    
            var sizeParameter = size != null ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(string));
    
            var lcrTypeParameter = lcrType != null ?
                new ObjectParameter("LcrType", lcrType) :
                new ObjectParameter("LcrType", typeof(string));
    
            var isDefinedParameter = isDefined != null ?
                new ObjectParameter("IsDefined", isDefined) :
                new ObjectParameter("IsDefined", typeof(string));
    
            var oXParameter = oX.HasValue ?
                new ObjectParameter("OX", oX) :
                new ObjectParameter("OX", typeof(decimal));
    
            var oYParameter = oY.HasValue ?
                new ObjectParameter("OY", oY) :
                new ObjectParameter("OY", typeof(decimal));
    
            var oAngleParameter = oAngle.HasValue ?
                new ObjectParameter("OAngle", oAngle) :
                new ObjectParameter("OAngle", typeof(decimal));
    
            var rowParameter = row.HasValue ?
                new ObjectParameter("Row", row) :
                new ObjectParameter("Row", typeof(int));
    
            var lXParameter = lX.HasValue ?
                new ObjectParameter("LX", lX) :
                new ObjectParameter("LX", typeof(decimal));
    
            var lYParameter = lY.HasValue ?
                new ObjectParameter("LY", lY) :
                new ObjectParameter("LY", typeof(decimal));
    
            var isMergeParameter = isMerge != null ?
                new ObjectParameter("IsMerge", isMerge) :
                new ObjectParameter("IsMerge", typeof(string));
    
            var standardImageParameter = standardImage != null ?
                new ObjectParameter("StandardImage", standardImage) :
                new ObjectParameter("StandardImage", typeof(byte[]));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(int));
    
            var furnaceLcrStandardValueParameter = furnaceLcrStandardValue.HasValue ?
                new ObjectParameter("FurnaceLcrStandardValue", furnaceLcrStandardValue) :
                new ObjectParameter("FurnaceLcrStandardValue", typeof(decimal));
    
            var furnaceLcrUnitCodeParameter = furnaceLcrUnitCode != null ?
                new ObjectParameter("FurnaceLcrUnitCode", furnaceLcrUnitCode) :
                new ObjectParameter("FurnaceLcrUnitCode", typeof(string));
    
            var furnaceLcrMaxValueParameter = furnaceLcrMaxValue.HasValue ?
                new ObjectParameter("FurnaceLcrMaxValue", furnaceLcrMaxValue) :
                new ObjectParameter("FurnaceLcrMaxValue", typeof(decimal));
    
            var furnaceLcrMinValueParameter = furnaceLcrMinValue.HasValue ?
                new ObjectParameter("FurnaceLcrMinValue", furnaceLcrMinValue) :
                new ObjectParameter("FurnaceLcrMinValue", typeof(decimal));
    
            var lXCompensationParameter = lXCompensation.HasValue ?
                new ObjectParameter("LXCompensation", lXCompensation) :
                new ObjectParameter("LXCompensation", typeof(decimal));
    
            var lYCompensationParameter = lYCompensation.HasValue ?
                new ObjectParameter("LYCompensation", lYCompensation) :
                new ObjectParameter("LYCompensation", typeof(decimal));
    
            var componentPackagingParameter = componentPackaging != null ?
                new ObjectParameter("ComponentPackaging", componentPackaging) :
                new ObjectParameter("ComponentPackaging", typeof(string));
    
            var sXParameter = sX.HasValue ?
                new ObjectParameter("SX", sX) :
                new ObjectParameter("SX", typeof(decimal));
    
            var sYParameter = sY.HasValue ?
                new ObjectParameter("SY", sY) :
                new ObjectParameter("SY", typeof(decimal));
    
            var adjustedAngleParameter = adjustedAngle.HasValue ?
                new ObjectParameter("AdjustedAngle", adjustedAngle) :
                new ObjectParameter("AdjustedAngle", typeof(decimal));
    
            var groupsParameter = groups.HasValue ?
                new ObjectParameter("Groups", groups) :
                new ObjectParameter("Groups", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Insert_Eng_XYData", productCodeParameter, positionParameter, boardIdParameter, boardSideParameter, isSMDParameter, materialCodeParameter, materialNameParameter, xParameter, yParameter, unitParameter, angleParameter, rXParameter, rYParameter, remarksParameter, creatorParameter, modifierParameter, standardCodeParameter, standardRotationParameter, sizeParameter, lcrTypeParameter, isDefinedParameter, oXParameter, oYParameter, oAngleParameter, rowParameter, lXParameter, lYParameter, isMergeParameter, standardImageParameter, sequenceParameter, furnaceLcrStandardValueParameter, furnaceLcrUnitCodeParameter, furnaceLcrMaxValueParameter, furnaceLcrMinValueParameter, lXCompensationParameter, lYCompensationParameter, componentPackagingParameter, sXParameter, sYParameter, adjustedAngleParameter, groupsParameter);
        }
    
        public virtual ObjectResult<P_Search_Eng_Bom_Result> P_Search_Eng_Bom(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Search_Eng_Bom_Result>("P_Search_Eng_Bom", productCodeParameter);
        }
    
        public virtual ObjectResult<P_Search_Eng_XYData_Result> P_Search_Eng_XYData(string productCode)
        {
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Search_Eng_XYData_Result>("P_Search_Eng_XYData", productCodeParameter);
        }
    }
}
