//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man_ReportLog
    {
        public int Row { get; set; }
        public string ReportCode { get; set; }
        public string Position { get; set; }
        public Nullable<int> BoardId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> BomSequence { get; set; }
        public string StationCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LcrType { get; set; }
        public Nullable<decimal> LcrStandardValue { get; set; }
        public string LcrUnitCode { get; set; }
        public Nullable<decimal> LcrMaxValue { get; set; }
        public Nullable<decimal> LcrMinValue { get; set; }
        public Nullable<decimal> LcrCheckValue { get; set; }
        public string Size { get; set; }
        public string ResultType { get; set; }
        public string CheckResult { get; set; }
        public string FailCause { get; set; }
        public byte[] StandardImage { get; set; }
        public byte[] CurrentImage { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public string IsSMD { get; set; }
        public Nullable<decimal> LX { get; set; }
        public Nullable<decimal> LY { get; set; }
        public Nullable<int> TypeValue { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string StandardCode { get; set; }
        public Nullable<decimal> StandardRotation { get; set; }
        public string IsDefined { get; set; }
        public Nullable<int> DefineWidth { get; set; }
        public Nullable<int> DefineHeight { get; set; }
        public Nullable<decimal> RX { get; set; }
        public Nullable<decimal> RY { get; set; }
        public Nullable<int> StationCodeRow { get; set; }
        public Nullable<int> CheckCount { get; set; }
        public string SubMaterialCode { get; set; }
        public string SubMaterialName { get; set; }
        public string Frequency { get; set; }
    
        public virtual Man_Report Man_Report { get; set; }
    }
}
