//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man_ReportItem
    {
        public string ReportCode { get; set; }
        public string Position { get; set; }
        public int BoardId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> BomSequence { get; set; }
        public string StationCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LcrType { get; set; }
        public Nullable<decimal> LcrStandardValue { get; set; }
        public string LcrUnitCode { get; set; }
        public Nullable<decimal> LcrMaxValue { get; set; }
        public Nullable<decimal> LcrMinValue { get; set; }
        public Nullable<decimal> MaxTolerance { get; set; }
        public Nullable<decimal> MinTolerance { get; set; }
        public Nullable<decimal> LcrCheckValue { get; set; }
        public string Size { get; set; }
        public string ResultType { get; set; }
        public string CheckResult { get; set; }
        public string FailCause { get; set; }
        public byte[] StandardImage { get; set; }
        public byte[] CurrentImage { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Angle { get; set; }
        public string IsSMD { get; set; }
        public Nullable<decimal> LX { get; set; }
        public Nullable<decimal> LY { get; set; }
        public Nullable<decimal> RX { get; set; }
        public Nullable<decimal> RY { get; set; }
        public Nullable<int> TypeValue { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string StandardCode { get; set; }
        public Nullable<decimal> StandardRotation { get; set; }
        public string IsDefined { get; set; }
        public Nullable<int> DefineWidth { get; set; }
        public Nullable<int> DefineHeight { get; set; }
        public Nullable<int> StationCodeRow { get; set; }
        public Nullable<decimal> LX2 { get; set; }
        public Nullable<decimal> LY2 { get; set; }
        public string ScreenPrinting { get; set; }
        public string SubMaterialCode { get; set; }
        public Nullable<int> CheckCount { get; set; }
        public string StandardOcrStr { get; set; }
        public string CheckOcrStr { get; set; }
        public string StandardOcrStr2 { get; set; }
        public string CheckOcrStr2 { get; set; }
        public string SubMaterialName { get; set; }
        public Nullable<int> FilterSort { get; set; }
        public string CheckLine { get; set; }
        public Nullable<decimal> OLcrStandardValue { get; set; }
        public Nullable<decimal> OLcrMaxValue { get; set; }
        public Nullable<decimal> OLcrMinValue { get; set; }
        public Nullable<int> Groups { get; set; }
        public string CheckType { get; set; }
        public Nullable<int> MinScore { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<decimal> Score2 { get; set; }
        public string StandardOcrStr3 { get; set; }
        public string CheckOcrStr3 { get; set; }
        public Nullable<decimal> Score3 { get; set; }
        public string StandardOcrStr4 { get; set; }
        public string CheckOcrStr4 { get; set; }
        public Nullable<decimal> Score4 { get; set; }
        public string StandardOcrStr5 { get; set; }
        public string CheckOcrStr5 { get; set; }
        public Nullable<decimal> Score5 { get; set; }
        public string StandardOcrStr6 { get; set; }
        public string CheckOcrStr6 { get; set; }
        public Nullable<decimal> Score6 { get; set; }
        public string StandardOcrStr7 { get; set; }
        public string CheckOcrStr7 { get; set; }
        public Nullable<decimal> Score7 { get; set; }
        public string StandardOcrStr8 { get; set; }
        public string CheckOcrStr8 { get; set; }
        public Nullable<decimal> Score8 { get; set; }
        public Nullable<decimal> SX { get; set; }
        public Nullable<decimal> SY { get; set; }
        public string ToleranceType { get; set; }
        public string OLcrUnitCode { get; set; }
        public string Frequency { get; set; }
        public int XYGroups { get; set; }
        public bool ErrorBoard { get; set; }
    
        public virtual Man_Report Man_Report { get; set; }
    }
}
