//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man_ComponentCheck
    {
        public long Row { get; set; }
        public string ProductCode { get; set; }
        public string PLCode { get; set; }
        public string DeviceNo { get; set; }
        public string StationCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LcrType { get; set; }
        public Nullable<decimal> LcrStandardValue { get; set; }
        public string LcrUnitCode { get; set; }
        public Nullable<decimal> LcrMaxValue { get; set; }
        public Nullable<decimal> LcrMinValue { get; set; }
        public Nullable<decimal> LcrCheckValue { get; set; }
        public string ResultType { get; set; }
        public string CheckResult { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
