//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Error
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string Operator { get; set; }
        public string IpAddress { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorWhere { get; set; }
        public string ErrorObject { get; set; }
        public string ErrorEvent { get; set; }
        public string ErrorLine { get; set; }
    }
}
