//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Option
    {
        public string OptionCode { get; set; }
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
        public string TypeCode { get; set; }
        public string IsVisible { get; set; }
        public string Remarks { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string ValueType { get; set; }
        public string ValueStyle { get; set; }
    }
}
