//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Lang
    {
        public long LangId { get; set; }
        public string AppName { get; set; }
        public string FormName { get; set; }
        public string Parent { get; set; }
        public Nullable<bool> IsMsg { get; set; }
        public string ComponetName { get; set; }
        public string PropName { get; set; }
        public string Default { get; set; }
        public string ZH_CN { get; set; }
        public string ZH_TW { get; set; }
        public string EN_US { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
