//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Eng_MeterOptionItem
    {
        public int 行 { get; set; }
        public string 操作码 { get; set; }
        public string 元件类型 { get; set; }
        public Nullable<decimal> 最小值 { get; set; }
        public string 最小值单位 { get; set; }
        public Nullable<decimal> 最大值 { get; set; }
        public string 最大值单位 { get; set; }
        public string 测试类型 { get; set; }
        public string 测试频率 { get; set; }
        public string 测试电压 { get; set; }
        public string 量程类型 { get; set; }
        public string 量程 { get; set; }
        public Nullable<int> 失败次数 { get; set; }
        public string 测量速度 { get; set; }
        public string 测试内阻 { get; set; }
        public Nullable<int> 取值次数 { get; set; }
        public Nullable<decimal> 波动区间 { get; set; }
        public Nullable<decimal> 有效值下限 { get; set; }
        public string 下限单位 { get; set; }
        public Nullable<decimal> 有效值上限 { get; set; }
        public string 上限单位 { get; set; }
        public string 备注 { get; set; }
    }
}
