//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Bas_Material
    {
        public string 物料编码 { get; set; }
        public string 物料名称 { get; set; }
        public string 元件类型 { get; set; }
        public Nullable<decimal> 标准值 { get; set; }
        public string 单位 { get; set; }
        public Nullable<decimal> 最大值 { get; set; }
        public Nullable<decimal> 最小值 { get; set; }
        public string 尺寸 { get; set; }
        public Nullable<decimal> 公差上限 { get; set; }
        public Nullable<decimal> 公差下限 { get; set; }
        public string 公差类别 { get; set; }
        public string 备注 { get; set; }
    }
}
