//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_CompensationValue
    {
        public Nullable<decimal> LcrStandardValue { get; set; }
        public string LcrUnitCode { get; set; }
        public Nullable<decimal> LcrCompensationValue { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public long Row { get; set; }
        public long Sort { get; set; }
        public Nullable<decimal> LcrMaxValue { get; set; }
        public string LcrMaxValueUnitCode { get; set; }
        public Nullable<decimal> LcrMinValue { get; set; }
        public string LcrMinValueUnitCode { get; set; }
        public Nullable<decimal> LcrCompensationMaxValue { get; set; }
        public Nullable<decimal> LcrCompensationMinValue { get; set; }
        public Nullable<decimal> LcrPrecision { get; set; }
        public string LcrCompensationValueType { get; set; }
    }
}
