//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eng_Program()
        {
            this.Eng_Bom = new HashSet<Eng_Bom>();
            this.Eng_BomECN = new HashSet<Eng_BomECN>();
            this.Eng_Model = new HashSet<Eng_Model>();
            this.Eng_ProgramLog = new HashSet<Eng_ProgramLog>();
            this.Eng_ProgramOption = new HashSet<Eng_ProgramOption>();
            this.Eng_XYData = new HashSet<Eng_XYData>();
        }
    
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CustomerCode { get; set; }
        public string BomVersion { get; set; }
        public string BoardSide { get; set; }
        public string BOMPositionSeparator { get; set; }
        public string STPositionSeparator { get; set; }
        public string RuleCode { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string OptionCode { get; set; }
        public Nullable<int> TopFixedPoint { get; set; }
        public Nullable<int> BottomFixedPoint { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
        public Nullable<int> BoardQty { get; set; }
        public Nullable<int> PanelRow { get; set; }
        public Nullable<int> PanelColumn { get; set; }
        public string SplitPositionSeparator { get; set; }
        public string Remarks2 { get; set; }
        public string PositionPrefixType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_Bom> Eng_Bom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_BomECN> Eng_BomECN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_Model> Eng_Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ProgramLog> Eng_ProgramLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ProgramOption> Eng_ProgramOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_XYData> Eng_XYData { get; set; }
    }
}
