//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ParseRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eng_ParseRule()
        {
            this.Eng_ParseRuleExpression = new HashSet<Eng_ParseRuleExpression>();
            this.Eng_ParseRuleReplace = new HashSet<Eng_ParseRuleReplace>();
            this.Eng_ParseRuleSeparator = new HashSet<Eng_ParseRuleSeparator>();
            this.Eng_ParseRuleToleranceC = new HashSet<Eng_ParseRuleToleranceC>();
            this.Eng_ParseRuleToleranceL = new HashSet<Eng_ParseRuleToleranceL>();
            this.Eng_ParseRuleToleranceR = new HashSet<Eng_ParseRuleToleranceR>();
        }
    
        public string RuleCode { get; set; }
        public string RuleName { get; set; }
        public string NoSeparator { get; set; }
        public string DigitsMethod { get; set; }
        public string UnitSymbolR { get; set; }
        public string UnitSymbolC { get; set; }
        public string TypeSymbol { get; set; }
        public string TypeSymbolR { get; set; }
        public string TypeSymbolC { get; set; }
        public string TypeSymbolO { get; set; }
        public string UnitDefaultR { get; set; }
        public string UnitDefaultC { get; set; }
        public string ToleranceDefaultR { get; set; }
        public string ToleranceDefaultC { get; set; }
        public string RuleType { get; set; }
        public string IsVisible { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string UnitSymbolL { get; set; }
        public string TypeSymbolL { get; set; }
        public string UnitDefaultL { get; set; }
        public string ToleranceDefaultL { get; set; }
        public string UnitMiddle { get; set; }
        public string UnitMiddleR { get; set; }
        public string TypeSymbolD { get; set; }
        public int TypeRuleDBegin { get; set; }
        public int TypeRuleDEnd { get; set; }
        public string TypeRuleDCode { get; set; }
        public string TypePositionD { get; set; }
        public string ToleranceLetter { get; set; }
        public string ToleranceAfterStandard { get; set; }
        public string TypeSymbolI { get; set; }
        public string TypeSymbolT { get; set; }
        public string AnalyzePriority { get; set; }
        public int TypeRuleRBegin { get; set; }
        public int TypeRuleREnd { get; set; }
        public string TypeRuleRCode { get; set; }
        public int TypeRuleCBegin { get; set; }
        public int TypeRuleCEnd { get; set; }
        public string TypeRuleCCode { get; set; }
        public int TypeRuleLBegin { get; set; }
        public int TypeRuleLEnd { get; set; }
        public string TypeRuleLCode { get; set; }
        public int TypeRuleTBegin { get; set; }
        public int TypeRuleTEnd { get; set; }
        public string TypeRuleTCode { get; set; }
        public int TypeRuleIBegin { get; set; }
        public int TypeRuleIEnd { get; set; }
        public string TypeRuleICode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleExpression> Eng_ParseRuleExpression { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleReplace> Eng_ParseRuleReplace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleSeparator> Eng_ParseRuleSeparator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleToleranceC> Eng_ParseRuleToleranceC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleToleranceL> Eng_ParseRuleToleranceL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ParseRuleToleranceR> Eng_ParseRuleToleranceR { get; set; }
    }
}
