//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eng_Model()
        {
            this.Eng_ModelItem = new HashSet<Eng_ModelItem>();
        }
    
        public string ProductCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LCRType { get; set; }
        public Nullable<bool> HasPub { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string RealMaterialCode { get; set; }
        public string RealMaterialName { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> RedLight { get; set; }
        public Nullable<int> GreenLight { get; set; }
        public Nullable<int> BlueLight { get; set; }
        public Nullable<decimal> AngleDifference { get; set; }
    
        public virtual Eng_Program Eng_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eng_ModelItem> Eng_ModelItem { get; set; }
    }
}
