//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ModelItem
    {
        public string ProductCode { get; set; }
        public string MaterialCode { get; set; }
        public byte[] mPicture { get; set; }
        public Nullable<int> mPW { get; set; }
        public Nullable<int> mPH { get; set; }
        public Nullable<decimal> mZoomRatio { get; set; }
        public Nullable<decimal> mDPI { get; set; }
        public int Id { get; set; }
        public Nullable<int> Groups { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<bool> Polarity { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public string OCRStr { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<int> PLeft { get; set; }
        public Nullable<int> PTop { get; set; }
        public Nullable<int> Pw { get; set; }
        public Nullable<int> Ph { get; set; }
        public byte[] Picture2 { get; set; }
        public Nullable<int> PLeft2 { get; set; }
        public Nullable<int> PTop2 { get; set; }
        public Nullable<int> Pw2 { get; set; }
        public Nullable<int> Ph2 { get; set; }
        public string OCRStr2 { get; set; }
        public Nullable<int> Kind2 { get; set; }
        public Nullable<int> LCy { get; set; }
        public Nullable<int> HCy { get; set; }
        public Nullable<int> NA { get; set; }
        public Nullable<int> NB { get; set; }
        public Nullable<int> XA { get; set; }
        public Nullable<int> XB { get; set; }
        public Nullable<double> Hd { get; set; }
        public Nullable<int> Kind { get; set; }
        public Nullable<int> P1 { get; set; }
        public Nullable<int> P2 { get; set; }
        public Nullable<int> P3 { get; set; }
        public Nullable<int> P4 { get; set; }
        public Nullable<int> P5 { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public byte[] Picture3 { get; set; }
        public Nullable<int> PLeft3 { get; set; }
        public Nullable<int> PTop3 { get; set; }
        public Nullable<int> Pw3 { get; set; }
        public Nullable<int> Ph3 { get; set; }
        public string OCRStr3 { get; set; }
        public Nullable<int> Kind3 { get; set; }
        public byte[] Picture4 { get; set; }
        public Nullable<int> PLeft4 { get; set; }
        public Nullable<int> PTop4 { get; set; }
        public Nullable<int> Pw4 { get; set; }
        public Nullable<int> Ph4 { get; set; }
        public string OCRStr4 { get; set; }
        public Nullable<int> Kind4 { get; set; }
        public byte[] Picture5 { get; set; }
        public Nullable<int> PLeft5 { get; set; }
        public Nullable<int> PTop5 { get; set; }
        public Nullable<int> Pw5 { get; set; }
        public Nullable<int> Ph5 { get; set; }
        public string OCRStr5 { get; set; }
        public Nullable<int> Kind5 { get; set; }
        public byte[] Picture6 { get; set; }
        public Nullable<int> PLeft6 { get; set; }
        public Nullable<int> PTop6 { get; set; }
        public Nullable<int> Pw6 { get; set; }
        public Nullable<int> Ph6 { get; set; }
        public string OCRStr6 { get; set; }
        public Nullable<int> Kind6 { get; set; }
        public byte[] Picture7 { get; set; }
        public Nullable<int> PLeft7 { get; set; }
        public Nullable<int> PTop7 { get; set; }
        public Nullable<int> Pw7 { get; set; }
        public Nullable<int> Ph7 { get; set; }
        public string OCRStr7 { get; set; }
        public Nullable<int> Kind7 { get; set; }
        public byte[] Picture8 { get; set; }
        public Nullable<int> PLeft8 { get; set; }
        public Nullable<int> PTop8 { get; set; }
        public Nullable<int> Pw8 { get; set; }
        public Nullable<int> Ph8 { get; set; }
        public string OCRStr8 { get; set; }
        public Nullable<int> Kind8 { get; set; }
        public string Color { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string Color4 { get; set; }
        public string Color5 { get; set; }
        public string Color6 { get; set; }
        public string Color7 { get; set; }
        public string Color8 { get; set; }
    
        public virtual Eng_Model Eng_Model { get; set; }
    }
}
