//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ParseRuleExpression
    {
        public long Id { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string ApplicableType { get; set; }
        public string ComponentType { get; set; }
        public string Expression { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string RuleCode { get; set; }
    
        public virtual Eng_ParseRule Eng_ParseRule { get; set; }
    }
}
