//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_BomECN
    {
        public string ProductCode { get; set; }
        public int Row { get; set; }
        public string OperationType { get; set; }
        public string OldMaterialCode { get; set; }
        public string OldMaterialName { get; set; }
        public Nullable<int> OldQuantity { get; set; }
        public string OldPosition { get; set; }
        public string NewMaterialCode { get; set; }
        public string NewMaterialName { get; set; }
        public Nullable<int> NewQuantity { get; set; }
        public string NewPosition { get; set; }
        public string Remarks { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
    
        public virtual Eng_Program Eng_Program { get; set; }
    }
}
