//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Bom
    {
        public string ProductCode { get; set; }
        public int Row { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Position { get; set; }
        public string AllowSubstitute { get; set; }
        public string LcrType { get; set; }
        public Nullable<decimal> LcrStandardValue { get; set; }
        public string LcrUnitCode { get; set; }
        public Nullable<decimal> LcrMaxValue { get; set; }
        public Nullable<decimal> LcrMinValue { get; set; }
        public string Size { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> MaxTolerance { get; set; }
        public Nullable<decimal> MinTolerance { get; set; }
        public string Status { get; set; }
        public string ScreenPrinting { get; set; }
        public string ToleranceType { get; set; }
        public string ComponentPackaging { get; set; }
    
        public virtual Eng_Program Eng_Program { get; set; }
    }
}
