//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_MeterOptionItem
    {
        public string OptionCode { get; set; }
        public int Row { get; set; }
        public Nullable<int> PRI { get; set; }
        public string LcrType { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public string MinValueUnit { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public string MaxValueUnit { get; set; }
        public string FunctionType { get; set; }
        public string Frequency { get; set; }
        public string Voltage { get; set; }
        public string RangeType { get; set; }
        public string Range { get; set; }
        public Nullable<int> HoldTimes { get; set; }
        public string Speed { get; set; }
        public string Resistance { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<decimal> FRValue { get; set; }
        public Nullable<decimal> MinValidValue { get; set; }
        public string MinValidValueUnit { get; set; }
        public Nullable<decimal> MaxValidValue { get; set; }
        public string MaxValidValueUnit { get; set; }
        public string Remarks { get; set; }
    
        public virtual Eng_MeterOption Eng_MeterOption { get; set; }
    }
}
