//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man_Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Man_Report()
        {
            this.Man_ReportItem = new HashSet<Man_ReportItem>();
            this.Man_ReportLog = new HashSet<Man_ReportLog>();
            this.Man_ReportInspectionItems = new HashSet<Man_ReportInspectionItems>();
        }
    
        public string ReportCode { get; set; }
        public string BoardSide { get; set; }
        public byte[] Picture { get; set; }
        public string PicturePath { get; set; }
        public string IsAdjusted { get; set; }
        public string P1 { get; set; }
        public Nullable<decimal> X1 { get; set; }
        public Nullable<decimal> Y1 { get; set; }
        public string P2 { get; set; }
        public Nullable<decimal> X2 { get; set; }
        public Nullable<decimal> Y2 { get; set; }
        public string P3 { get; set; }
        public Nullable<decimal> X3 { get; set; }
        public Nullable<decimal> Y3 { get; set; }
        public string PLCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string WoCode { get; set; }
        public string LotNumber { get; set; }
        public Nullable<int> BoardQty { get; set; }
        public string CheckResult { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> AutomationQty { get; set; }
        public Nullable<int> ManualQty { get; set; }
        public Nullable<int> PassQty { get; set; }
        public Nullable<int> FailQty { get; set; }
        public Nullable<int> MissQty { get; set; }
        public string IsForceFinish { get; set; }
        public string FinishedBy { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public string IsVisible { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string OptionCode { get; set; }
        public Nullable<int> CheckTime { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> RQty { get; set; }
        public Nullable<int> CQty { get; set; }
        public Nullable<int> LQty { get; set; }
        public Nullable<int> DQty { get; set; }
        public Nullable<int> BQty { get; set; }
        public Nullable<int> OQty { get; set; }
        public Nullable<int> TQty { get; set; }
        public Nullable<int> IQty { get; set; }
        public Nullable<int> SmdQty { get; set; }
        public Nullable<int> NoSmdQty { get; set; }
        public string P4 { get; set; }
        public Nullable<decimal> X4 { get; set; }
        public Nullable<decimal> Y4 { get; set; }
        public string @class { get; set; }
        public Nullable<int> BatchQty { get; set; }
        public string CheckType { get; set; }
        public string P5 { get; set; }
        public Nullable<decimal> X5 { get; set; }
        public Nullable<decimal> Y5 { get; set; }
        public string P6 { get; set; }
        public Nullable<decimal> X6 { get; set; }
        public Nullable<decimal> Y6 { get; set; }
        public Nullable<int> FixedPoint { get; set; }
        public string PCBVersion { get; set; }
        public string BomVersion { get; set; }
        public Nullable<int> PanelRow { get; set; }
        public Nullable<int> PanelColumn { get; set; }
        public Nullable<int> B1 { get; set; }
        public Nullable<int> B2 { get; set; }
        public Nullable<int> B3 { get; set; }
        public Nullable<int> B4 { get; set; }
        public Nullable<int> B5 { get; set; }
        public Nullable<int> B6 { get; set; }
        public Nullable<bool> IsFurnace { get; set; }
        public string IsQACheck { get; set; }
        public string QAChecker { get; set; }
        public Nullable<System.DateTime> QACheckTime { get; set; }
        public string IsCheckNoSMD { get; set; }
        public string DeviceName { get; set; }
        public string ProgramStatus { get; set; }
        public string Remarks2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Man_ReportItem> Man_ReportItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Man_ReportLog> Man_ReportLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Man_ReportInspectionItems> Man_ReportInspectionItems { get; set; }
    }
}
