//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Man_ComponentSize
    {
        public int SizeId { get; set; }
        public string SizeCode { get; set; }
        public Nullable<int> PixelWidth { get; set; }
        public Nullable<int> PixelHeight { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsOCR { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> PhysicalSizeLength { get; set; }
        public Nullable<decimal> PhysicalSizeWidth { get; set; }
        public Nullable<decimal> SWidth { get; set; }
        public Nullable<decimal> SHeight { get; set; }
    }
}
