//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_RolePower
    {
        public string RoleCode { get; set; }
        public string PowerCode { get; set; }
        public string Remarks { get; set; }
    
        public virtual Sys_Power Sys_Power { get; set; }
        public virtual Sys_Role Sys_Role { get; set; }
    }
}
