//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSP_SJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Power
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Power()
        {
            this.Sys_RolePower = new HashSet<Sys_RolePower>();
        }
    
        public string ParentPowerCode { get; set; }
        public string PowerCode { get; set; }
        public string Name { get; set; }
        public string TypeCode { get; set; }
        public string Module { get; set; }
        public string ClassName { get; set; }
        public string IsSheet { get; set; }
        public string IsNavigation { get; set; }
        public Nullable<int> NavLevel { get; set; }
        public string IsExpand { get; set; }
        public string IsVisible { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_RolePower> Sys_RolePower { get; set; }
    }
}
